export type {
  AgentDef,
  BranchPrDetectionResult,
  ChangedFile,
  CommitInfo,
  CoverageFileSummary,
  CoverageMetricSummary,
  CoverageSummary,
  CreateTaskResult,
  FileDiffResult,
  ImportableWorktree,
  MergeResult,
  MergeStatus,
  PrCheckBucket,
  PrCheckRun,
  PrChecksOverall,
  PrChecksUpdatePayload,
  PtyOutput,
  HulyIssue,
  StepEntry,
  TranscriptEvent,
  TranscriptEventInput,
  TranscriptEventKind,
  WorktreeStatus,
} from '../../electron/ipc/shared-types';

export type { UpdatePhase, UpdateStatus } from '../../electron/ipc/updater';
